In [10]:
#Exercise 10
import numpy as np
exams = np.array([[78, 85, 92, 88],[65, 72, 68, 70],[90, 88, 95, 92],[55, 60, 58, 62],[82, 79, 85, 80]])
bonus = np.array([5, 10, 5, 10])
mltp = np.array([1.0, 1.1, 0.95, 1.15, 1.0])
print(exams)
exams = exams + bonus
print(exams)
exams = exams * mltp[:, None]
print(exams)

[[78 85 92 88]
 [65 72 68 70]
 [90 88 95 92]
 [55 60 58 62]
 [82 79 85 80]]
[[ 83  95  97  98]
 [ 70  82  73  80]
 [ 95  98 100 102]
 [ 60  70  63  72]
 [ 87  89  90  90]]
[[83.   95.   97.   98.  ]
 [77.   90.2  80.3  88.  ]
 [90.25 93.1  95.   96.9 ]
 [69.   80.5  72.45 82.8 ]
 [87.   89.   90.   90.  ]]
